<?php 

if( ! function_exists( 'road_get_slider_setting' ) ) {
	function road_get_slider_setting() {
		return array(
			array(
				'type'        => 'dropdown',
				'holder'      => 'div',
				'heading'     => esc_html__( 'Style', 'ecolife' ),
				'param_name'  => 'style',
				'value'       => array(
					__( 'Grid view (default)', 'ecolife' )      => 'product-grid',
					__( 'Grid view (progess bar)', 'ecolife' ) => 'product-grid-progessbar',
					__( 'List view ', 'ecolife' )               => 'product-list',
					__( 'List view (progess bar)', 'ecolife' ) => 'product-list product-list-progessbar',
				),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Enable slider', 'ecolife' ),
				'description' => __( 'If slider is enabled, the "column" ins General group is the number of rows ', 'ecolife' ),
				'param_name'  => 'enable_slider',
				'value'       => true,
				'save_always' => true, 
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'holder'     => 'div',
				'heading'    => __( 'Number of columns (screen: over 1500px)', 'ecolife' ),
				'param_name' => 'items_1500up',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '4', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 1200px - 1499px)', 'ecolife' ),
				'param_name' => 'items_1200_1499',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '4', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 992px - 1199px)', 'ecolife' ),
				'param_name' => 'items_992_1199',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '4', 'ecolife' ),
			), 
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 768px - 991px)', 'ecolife' ),
				'param_name' => 'items_768_991',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '3', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 640px - 767px)', 'ecolife' ),
				'param_name' => 'items_640_767',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '2', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 480px - 639px)', 'ecolife' ),
				'param_name' => 'items_480_639',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '2', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 375px - 479px)', 'ecolife' ),
				'param_name' => 'items_375_479',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: under 374px)', 'ecolife' ),
				'param_name' => 'items_0_374',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
			),
			array(
				'type'        => 'dropdown',
				'heading'     => __( 'Navigation', 'ecolife' ),
				'param_name'  => 'navigation',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
				'value'       => array(
					__( 'Yes', 'ecolife' ) => true,
					__( 'No', 'ecolife' )  => false,
				),
			),
			array(
				'type'        => 'dropdown',
				'heading'     => __( 'Pagination', 'ecolife' ),
				'param_name'  => 'pagination',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
				'value'       => array(
					__( 'No', 'ecolife' )  => false,
					__( 'Yes', 'ecolife' ) => true,
				),
			),
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Item Margin (unit: pixel)', 'ecolife' ),
				'param_name'  => 'item_margin',
				'value'       => 30,
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Slider speed number (unit: second)', 'ecolife' ),
				'param_name'  => 'speed',
				'value'       => '500',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Slider loop', 'ecolife' ),
				'param_name'  => 'loop',
				'value'       => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Slider Auto', 'ecolife' ),
				'param_name'  => 'auto',
				'value'       => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'dropdown',
				'holder'      => 'div',
				'heading'     => esc_html__( 'Navigation style', 'ecolife' ),
				'param_name'  => 'navigation_style',
				'group'       => __( 'Slider Options', 'ecolife' ),
				'value'       => array(
					'Navigation center horizontal'	=> 'navigation-style1',
					'Navigation top-right'	=> 'navigation-style2',
				),
			),
		);
	}
}

if( ! function_exists( 'roadthemes_get_slider_testimonial_setting' ) ) {
	function roadthemes_get_slider_testimonial_setting() {
		return array(
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: over 1201px)', 'ecolife' ),
				'param_name' => 'items_1201up',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 993px - 1200px)', 'ecolife' ),
				'param_name' => 'items_993_1200',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			), 
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 769px - 992px)', 'ecolife' ),
				'param_name' => 'items_769_992',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 641px - 768px)', 'ecolife' ),
				'param_name' => 'items_641_768',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: 360px - 640px)', 'ecolife' ),
				'param_name' => 'items_360_640',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Number of columns (screen: under 360px)', 'ecolife' ),
				'param_name' => 'items_0_359',
				'group'      => __( 'Slider Options', 'ecolife' ),
				'value'      => esc_html__( '1', 'ecolife' ),
				'save_always'=> true,
			),
			array(
				'type'        => 'dropdown',
				'heading'     => __( 'Navigation', 'ecolife' ),
				'param_name'  => 'navigation',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
				'value'       => array(
					__( 'No', 'ecolife' )  => false,
					__( 'Yes', 'ecolife' ) => true,
				),
			),
			array(
				'type'        => 'dropdown',
				'heading'     => __( 'Pagination', 'ecolife' ),
				'param_name'  => 'pagination',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
				'value'       => array(
					__( 'Yes', 'ecolife' ) => true,
					__( 'No', 'ecolife' )  => false,
				),
			),
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Item Margin (unit:pixel)', 'ecolife' ),
				'param_name'  => 'item_margin',
				'value'       => 30,
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Slider speed number (unit: second)', 'ecolife' ),
				'param_name'  => 'speed',
				'value'       => '500',
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Slider loop', 'ecolife' ),
				'param_name'  => 'loop',
				'value'       => false,
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Slider Auto', 'ecolife' ),
				'param_name'  => 'auto',
				'value'       => false,
				'save_always' => true,
				'group'       => __( 'Slider Options', 'ecolife' ),
			),
			array(
				'type'        => 'checkbox',
				'heading'     => __( 'Pagination with Thumbnail', 'ecolife' ),
				'param_name'  => 'thumbnail',
				'save_always' => true,
				'value'       => false,
			),
		);
	}
}